[package]
name = "meine-kleine-rust-puzzles"
version = "0.1.0"
authors = ["euclidthedark <euclidthedark@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="puzzles"
path="src/lib.rs"
